dataset:
    bench_info:
        num_classes: 20 # Adjust the value according to the number of classes handled by the benchmark.
    anno_info:
        format:
            file_path: "" # Insert the file path for the annotation.
    feat_info:
        format:
            dir_path: "" # Insert the directory path where the features are located.
            prefix: "" # Define this variable if you are using a prefix during preprocessing.
            type: "" # Define this variable if you are using a mid-term value during preprocessing.
            ext: "" # Define this variable if you are using an extension during preprocessing.
        meta: # Define and utilize preprocessing variables for the data.
            feat_stride: 4
            downsample_rate: 1
            num_frames: 16
            default_fps: ~
            max_seq_len: 2304
            trunc_thresh: 0.5
            crop_ratio: [0.9, 1.0]
    loader: # Set up the configurations related to the dataloader.
        pin_memory: false
        num_workers: 20
        seed: 1234567891
        batch_size: 2
        max_seq_len: ${dataset.feat_info.meta.max_seq_len}
        padding_value: 0.0
        max_div_factor: 1